name: synapses-thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pillow
  - scikit-image
  - tifffile
  - jupyter
  - ipykernel
  - pip
  - pip:
      - scikit-posthocs
